### ISSUE TITLE
TypeError when installing Trackmania (2020) on 0.5.9 beta1

### ISSUE THREAD

**Issue by baduhai** [lutris/lutris#3683]
I get the following error when trying to install Trackmania:

`TypeError("create_prefix() got an unexpected keyword argument 'env'")`

This error is not reproducible in 0.5.8 

I should add I'm on Arch Linux.

**Comment by crebwyllion** [comment]
I'm on Fedora 34 and I'm getting similar errors when I try to install Dishonored - Definitive Edition from GOG (not using any particular script) and also Final Fantasy XIV when installing using the XIVLauncher script. I haven't tried the script for the official client.

**Comment by tannisroot** [comment]
Offending commit is https://github.com/lutris/lutris/commit/341537ca46d21c4feaa1e4ac48805fc110ec4543

**Comment by strycore** [comment]
Fixed, the winemenubuilder stuff should be limited to wineexec
