### ISSUE TITLE
after upgrade to python 3.11: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

### ISSUE THREAD

**Issue by AngryPenguinPL** [lutris/lutris#4420]
Hi.
After upgrading system python to 3.11 on OpenMandriva Cooker I see that lutris no longer launching.
I see this error:
```
lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 39, in <module>
    from lutris.game import Game, export_game, import_game
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 24, in <module>
    from lutris.runners import InvalidRunner, import_runner, wine
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 9, in <module>
    from lutris.runners.commands.wine import (  # noqa: F401 pylint: disable=unused-import
  File "/usr/lib/python3.11/site-packages/lutris/runners/commands/wine.py", line 16, in <module>
    from lutris.util.wine.prefix import WinePrefixManager
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/prefix.py", line 4, in <module>
    from lutris.util import joypad, system
  File "/usr/lib/python3.11/site-packages/lutris/util/joypad.py", line 10, in <module>
    import evdev
  File "/usr/lib64/python3.11/site-packages/evdev/__init__.py", line 5, in <module>
    from evdev.device import DeviceInfo, InputDevice, AbsInfo, EvdevError
  File "/usr/lib64/python3.11/site-packages/evdev/device.py", line 12, in <module>
    from evdev.eventio_async import EventIO, EvdevError
  File "/usr/lib64/python3.11/site-packages/evdev/eventio_async.py", line 63, in <module>
    class ReadIterator(object):
  File "/usr/lib64/python3.11/site-packages/evdev/eventio_async.py", line 88, in ReadIterator
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

Trying on 0.5.10.1 and 0.5.11-beta1

**Comment by danieljohnson2** [comment]
This is not Lutris, actually, it's the 'evdev' package that we're using for joypad support. evdev 1.5 is not compatible with Python 3.11, you need 1.6.

However, this is an awkward situation where Python 3.11 made a deliberate breaking change underneath evdev, and we ought to try to deal with it gracefully.

I've added an exception handler so that if this happens, Lutris logs an error and continues as if evdev was not installed.

Lutris already tolerates it when evdev is just missing, so you could also work around this by uninstalling the old evdev package you have installed.

But I would appreciate it if you could try the master version of Lutris (which I just updated) to see if my 'fix' works.

You do not need to install it; download or clone it, and run the script in 'bin/lutris' inside of it.

**Comment by AngryPenguinPL** [comment]
Yes, I can confirm that this commit fix my issue. Testing it on master and works fine.

Thanks.
