### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'service'

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#3207]
Updated to the latest git and got this on the terminal:

```
DEBUG    2020-10-17 07:51:15,301 [lutriswindow.set_service:311]:Setting service to None
Traceback (most recent call last):
  File "~/src/lutris/lutris/gui/application.py", line 219, in do_activate
    self.window = LutrisWindow(application=self)
  File "~/src/lutris/lutris/gui/lutriswindow.py", line 105, in __init__
    self.set_service(self.filters.get("service"))
  File "~/src/lutris/lutris/gui/lutriswindow.py", line 314, in set_service
    self.unset_service()
  File "~/src/lutris/lutris/gui/lutriswindow.py", line 322, in unset_service
    self.game_store.service = None
AttributeError: 'NoneType' object has no attribute 'service'
```

**Comment by veksha** [comment]
7d388429dc12486760a53634e3deee7de3733bf3 is the first bad commit
    Load correct default icon size for services

**Comment by pakro** [comment]
The problem probably could be solved by checking for game_store [see `// 1`] and if it is not present just do not set `game_store.service = None`. But I'm not sure if this is the real cause. 

```
    def set_service(self, service_name):
        if self.service and self.service.id == service_name:
            return self.service

        if not service_name:
            self.unset_service()
        self.service = services.get_services()[service_name]()
        if self.game_store:
            self.game_store.service = self.service
        return self.service

    def unset_service(self):
        self.service = None
        self.game_store.service = None // 1
        self.tabs_box.hide()

```

**Comment by veksha** [comment]
I think this is fixed now.
