### ISSUE TITLE
Lutris restarts when trying to use an installer from website

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2565]
If I click on the "Install" button on any installer from Lutris.Net, instead of a prompt to install a game, Lutris just restarts, which makes me unable to install any game. There's a backtrace when Lutris launches:
```
INFO     2020-01-02 11:37:04,763 [application.do_command_line:219]:Running Lutris 0.5.4
INFO     2020-01-02 11:37:04,763 [startup.check_driver:54]:Using NVIDIA drivers 440.43.01 for x86_64
INFO     2020-01-02 11:37:04,763 [startup.check_driver:60]:GPU: GeForce GTX 1070
INFO     2020-01-02 11:37:04,763 [startup.check_driver:77]:GPU: 10DE:1B81 1458:3772 using nvidia drivers
INFO     2020-01-02 11:37:04,783 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-01-02 11:37:04,784 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2020-01-02 11:37:05,056 [http.get:65]:GET https://lutris.net/api/runtime
INFO     2020-01-02 11:37:05,062 [lutriswindow.toggle_connection:653]:Connected to lutris.net as citrusalex
DEBUG    2020-01-02 11:37:05,062 [http.get:65]:GET https://lutris.net/api/games/library/citrusalex
DEBUG    2020-01-02 11:37:05,068 [store.get_missing_media:211]:Requesting missing icons from API for apitrace, hades, test, pokemon-crystal-version, detroit-become-human, legend-of-zelda-windwaker
DEBUG    2020-01-02 11:37:05,068 [http.get:65]:GET https://lutris.net/api/games
DEBUG    2020-01-02 11:37:05,452 [api.get_game_api_page:132]:Loaded 5 games from page 1
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 317, in do_command_line
    self.set_tray_icon()
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 473, in set_tray_icon
    self.tray = LutrisStatusIcon(application=self)
  File "/usr/lib/python3.8/site-packages/lutris/gui/widgets/status_icon.py", line 20, in __init__
    self.icon.set_menu(self.menu)
AttributeError: 'LutrisTray' object has no attribute 'set_menu'
```

**Comment by tannisroot** [comment]
Caused by https://github.com/lutris/lutris/commit/fb112045903f2e7f2ad1d806f86e3c2983946142

**Comment by strycore** [comment]
There is no code that would ever make Lutris restart so I'm just going to ignore that and just fix the bug from the stacktrace
