### ISSUE TITLE
Multiple issues on Arch

### ISSUE THREAD

**Issue by ElryGH** [lutris/lutris#5671]
### Bug description

Both pacman lutris 0.5.17-7 and lutris-git have a problem, where this button:
![image](https://github.com/user-attachments/assets/835d0e4e-02d7-4d4b-9415-2de43a2faf21)
Doesnt do anything and just says "Waiting for response" forever.
![image](https://github.com/user-attachments/assets/02eac26c-d70a-44ab-ad28-a94514f44ea7)

Using the settings to Download wine works on lutris-git, but instantly crashes lutris 0.5.17-7 (pacman).

Clicking on Download Updates in Settings kinda works on lutris-git, but again lutris 0.5.17-7 (pacman) crashes instantly.
But on lutris-git i get this issue tho after a few Downloads, when the only thing left is "Downloading icons"
![image](https://github.com/user-attachments/assets/dd3fd671-b762-4ee7-8685-0dfb7351f195)

```
'NoneType' object has no attribute 'get_children'

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 57, in discarding_result
    function(*args, **kwargs)

  File "/usr/lib/python3.12/site-packages/lutris/gui/dialogs/runner_install.py", line 185, in runner_fetch_cb
    for child_widget in self.vbox.get_children():
                        ^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'get_children'
```

### How to Reproduce

1. Install lutris or lutris-git on Arch
2. See Bug description

### Expected behavior

I should be able to download Wine or Updates without any problems.

### Log output

```shell
INFO     2024-10-22 15:31:45,038 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-10-22 15:31:45,202 [startup.run_all_checks:120]:NVIDIA GeForce RTX 4060 (10de:2882 19da:1726 nvidia) Driver 560.35.03
DEBUG    2024-10-22 15:31:45,280 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-10-22 15:31:45,282 [xrandr._get_vidmodes:18]:Retrieving 59 video modes from XrandR
DEBUG    2024-10-22 15:31:45,316 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-10-22 15:31:45,332 [api.check_stale_runtime_versions:52]:Modified at Tue 22 Oct 2024 03:18:36 PM , will update after Tue 22 Oct 2024 09:18:36 PM 

(lutris:138247): Gtk-WARNING **: 15:31:45.332: Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Inhibit” on object at path /org/freedesktop/portal/desktop
ERROR    2024-10-22 15:31:45,339 [style_manager._call_cb:87]:Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/style_manager.py", line 80, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
DEBUG    2024-10-22 15:31:45,340 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-10-22 15:31:46,317 [http._request:88]:POST https://lutris.net/api/users/library?since=1729603269
DEBUG    2024-10-22 15:31:47,951 [api.get_runners:170]:Retrieving runners
DEBUG    2024-10-22 15:31:47,951 [application.show_window:394]:Showing window RunnerInstallDialogwine
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Hyprwave rolling n/a
Arch: x86_64
Kernel: 6.11.4-arch2-1
Desktop: Hyprland
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 5900X 12-Core Processor
Physical cores: 12
Logical cores: 24
[Memory]
RAM: 31.2 GB
Swap: 0.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 4060/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 560.35.03
OpenGL Core: 4.6.0 NVIDIA 560.35.03
OpenGL ES: OpenGL ES 3.2 NVIDIA 560.35.03
Vulkan Version: 1.3.295
Vulkan Drivers: NVIDIA GeForce RTX 4060 (1.3.280)
```

**Comment by danieljohnson2** [comment]
Some of that is apparently fixed in master, which is what ``lutris-git`` is giving you.

That crash you've documented though is still there; that happens if you close that install-wine-runners dialog while it is waiting for Lutris.net to get back to it. It crashes when it finally gets an error or the response, but the dialog is no longer there it receive it. I've made it just do nothing if that happens.

That tells me that if you'd waiting long enough, something would have happened- either the version list would appear or an error would. Maybe try again and wait longer?

**Comment by ElryGH** [comment]
@danieljohnson2 
Well the problem wasnt any of that....
I disabled IPV6 and everything worked fine, so enabling IPV6 for Lutris and lutris.net would be an option ? Its 2024, why is Lutris not IPV6 compatible...

**Comment by danieljohnson2** [comment]
Maybe you should bring that up on [the website's repo](https://github.com/lutris/website).
