### ISSUE TITLE
Lutris - Unable to get runners

### ISSUE THREAD

**Issue by Leopard1907** [lutris/lutris#1140]
So , i have this strange problem. Lutris doesn't let me to manage Wine versions etc.

Gives that error.

![lutris](https://user-images.githubusercontent.com/24878978/46320821-d0257380-c5e8-11e8-9f72-8a642d3a682b.png)

Output of `lutris -d`:

`ERROR    2018-10-02 02:09:31,774 [dxvk]:<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
WARNING  2018-10-02 02:09:31,870 [application]:This version of Gtk doesn't support set_option_context_summary
ERROR    2018-10-02 02:09:32,202 [http]:Unable to connect to server (https://lutris.net/api/runtime): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
DEBUG    2018-10-02 02:09:32,206 [api]:Fetching game library
DEBUG    2018-10-02 02:09:32,399 [steam]:Watching Steam folder /home/asus/.local/share/Steam/steamapps
DEBUG    2018-10-02 02:09:32,400 [steam]:Watching Steam folder /Steam Oyunları/steamapps
ERROR    2018-10-02 02:09:40,479 [http]:Unable to connect to server (https://lutris.net/api/runners/wine): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
ERROR    2018-10-02 02:09:43,854 [http]:Unable to connect to server (https://lutris.net/api/runners/wine): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
ERROR    2018-10-02 02:10:57,897 [http]:Unable to connect to server (https://lutris.net/api/runners/wine): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
`

Though i can ping to Lutris.net just fine:

![lutris2](https://user-images.githubusercontent.com/24878978/46320893-25fa1b80-c5e9-11e8-9fb2-04139237eb40.png)

Distro: Linux Mint 18.3

**Comment by AccountOneOff** [comment]
Duplicate #1134

**Comment by Leopard1907** [comment]
I think that has to do with libssl. My version is 1.0.2 something.

If it needs libssl 1.1 maybe that is the root cause.

Ukuu is in a similar state. It complains about libssl 1.1.0 or newer.

**Comment by tannisroot** [comment]
If this not an issue caused by Lutris itself, can you close it?

**Comment by Leopard1907** [comment]
No , it is probably Lutris related. Same piece of software was working 2 months ago. 

So i assume that is caused by targeting Ubuntu 18.04 and it's packages as minimals.

I'm just saying maybe that is be the reason.

Also if you look at the other report , i'm not the only one experiencing this.

**Comment by strycore** [comment]
we changed the SSL certificates to the CloudFlare ones but they should be valid, it seems to be an issue in some weird edge case.

**Comment by strycore** [comment]
For anyone with this issue can you give me:

- you linux distribution
- the version of libssl installed on your system
- your geographical location (country or region is enough)

**Comment by Leopard1907** [comment]
@strycore

- Linux Mint 18.3
- libssl: 1.0.2 g 
- Turkey
-If that is needed i can provide ISP information too , maybe some soft blocking goes on?

( You can also check other Ubuntu libssl versions per base from here )


https://packages.ubuntu.com/search?keywords=libssl

**Comment by Leopard1907** [comment]
So i just asked for another Turkey based Linux user and he can get runners.

His infos:

- Manjaro Linux
- libssl: 1.1.1
- Turkey
- He pings just fine to lutris.net 104.27.87.145 , just like i can

Other difference is ; his ISP.

Mine is Türksat Uydunet-internet , while his ISP is Turkcell Superonline.

https://store.steampowered.com/stats/content/

So there seems to be no country based blocking at all.

**Comment by Leopard1907** [comment]
https://support.cloudflare.com/hc/en-us/articles/115001186052-What-intermediates-and-roots-are-Cloudflare-issued-certs-signed-against-

Also tried this

openssl s_client -tls1_2 -connect lutris.net:443 -servername lutris.net 

But didn't help.

**Comment by goldsteal** [comment]
* linux distribution: Linux Mint 19 Tara (w kernel 4.18.14-041814-generic)
* libssl: 1.1.0g-2ubuntu4.1
* geographical location: Europe/Germany
* the ip address when pinging [lutris.net](http://lutris.net): 2606:4700:30::681b:baf5
* the ip address when pinging [www.lutris.net](http://www.lutris.net): 62.210.136.153
* the ip address when pinging [wiki.lutris.net](http://wiki.lutris.net): 2606:4700:30::681b:baf5

**Comment by Leopard1907** [comment]
@strycore

A small update ; also another user suffers from same problem. He connects with Vodafone mobile network and have the same problem.

He is from Turkey also.

**Comment by iLiwe** [comment]
Distro: Ubuntu
Libssl version: both libssl1.1 package and libssl1.0.0 package is installed on my system
IP i get when pinging lutris.net: 104.27.187.245
Country: Turkey
ISP (if needed): Turk Telekom

**Comment by tannisroot** [comment]
What happens if you use a VPN from another country or run it with torify?

**Comment by HeavenDest** [comment]
İ am from turkey and in live in ANKARA       ( Olayı bilen Türk varsa ingilizcem berbat yardımcı olun arkadaşlar ya  destfuat@gmail.com )

İ used xubuntu 18.04.1          64 bit 

my location : 39.926901,32.916155   or Turkey Ankara

i not know my libssl version

PING lutris.net (104.27.187.245) 56(84) bytes of data.
PING www.lutris.net (62.210.136.153) 56(84) bytes of data.
PING wiki.lutris.net (104.27.187.245) 56(84) bytes of data.

ISP (if needed): Turk Telekom


`DEBUG    2018-11-09 02:02:08,572 [http]:GET https://lutris.net/api/runtime
ERROR    2018-11-09 02:02:08,758 [http]:Unable to connect to server (https://lutris.net/api/runtime): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
DEBUG    2018-11-09 02:02:08,762 [api]:Fetching game library
INFO     2018-11-09 02:02:09,132 [lutriswindow]:Setting up view for first run
DEBUG    2018-11-09 02:02:09,133 [lutriswindow]:Syncing 1 icons
DEBUG    2018-11-09 02:02:09,138 [resources]:Requesting missing icons from API for 1 games
DEBUG    2018-11-09 02:02:09,139 [http]:GET https://lutris.net/api/games
ERROR    2018-11-09 02:02:09,269 [http]:Unable to connect to server (https://lutris.net/api/games): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/resources.py", line 45, in fetch_icons
    results = api.get_games(game_slugs=missing_media_slugs)
  File "/usr/lib/python3/dist-packages/lutris/api.py", line 102, in get_games
    response_data = get_game_api_page(game_slugs, page)
  File "/usr/lib/python3/dist-packages/lutris/api.py", line 93, in get_game_api_page
    len(response_data.get('results')), page)
AttributeError: 'NoneType' object has no attribute 'get'
INFO     2018-11-09 02:02:10,834 [application]:Shutting down Lutris
INFO     2018-11-09 02:02:10,847 [application]:Shutting down Lutris
`

**Comment by Azimech446** [comment]
Unfortunately i have that issue too. I can not login in lutris. 

Output of lutris-d
DEBUG    2018-11-24 16:02:12,542 [lutriswindow]:Showing splash screen
DEBUG    2018-11-24 16:02:12,572 [http]:GET https://lutris.net/api/runtime
ERROR    2018-11-24 16:02:12,745 [http]:Unable to connect to server (https://lutris.net/api/runtime): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>
DEBUG    2018-11-24 16:02:12,746 [api]:Fetching game library
DEBUG    2018-11-24 16:02:12,857 [steam]:Watching Steam folder /home/kemal/.local/share/Steam/steamapps
DEBUG    2018-11-24 16:02:12,938 [lutriswindow]:Showing splash screen
INFO     2018-11-24 16:02:12,939 [lutriswindow]:Setting up view for first run
ERROR    2018-11-24 16:02:22,293 [api]:Unable to connect to server (https://lutris.net/api/accounts/token): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>

Turkey
if needed my isp is TurkNet
1.1.0g-2ubuntu4.1 libssl version
18.04 lts ubuntu
ip address i get when pinging lutris.net : 104.27.187.245

**Comment by Azimech446** [comment]
I fixed that issue and what i make is upgrade from 18.04 lts to 18.10. but i want to use 18.04 lts, maybe one day lutris works on 18.04 and i can use

**Comment by rea987** [comment]
That's probably a side effect of government censorship on Internet in Turkey. Sometimes, a range of IPs are either got filtered and/or blocked which might cause intended affects on certain software. Another example is Spotify on Mint 17.3 which is unable to play ads that makes free accounts effectively ad-free in Turkey in that specific distro version; as I have never seen a report on that I presume that's again a distro version specific unavailable IP range in Turkey.

**Comment by Leopard1907** [comment]
I don't think that is related. Also i've never heard that Spotify issue though that is kinda normal ; people won't complain about it :D

If there is a really censorship going on ; how people here claim updating to 18.10 fixes that issue? 

Or GoldSteal in this issue ( which he locates in Germany ) suffers from that issue also?

**Comment by rea987** [comment]
@Leopard1907 No idea. Has @goldsteal ever used a VPN or Proxy which connects via a Turkish IP?

**Comment by Leopard1907** [comment]
I don't think so because there is no reason for it. That would be absurd :P

**Comment by rea987** [comment]
@Leopard1907 Not really, it highly unlikely that @goldsteal ever does that, but that's something I used to do; using VPN to get IP from Turkey while being abroad.

**Comment by strycore** [comment]
I don't think this is a censorship issue, but there is a routing issue that is specific to Turkey it seems.

There might be a problem with the current SSL setup that is only resolved on recent versions of libssl. 

Can anyone else confirm this Ubuntu 18.04 / Ubuntu 18.10 difference? (A dual boot with both would be best to check)

**Comment by Leopard1907** [comment]
@strycore I installed Ubuntu 18.10 into a VM on my Mint 18.3 machine and Lutris can get runners on 18.10

lutris -d output:

`WARNING  2018-11-25 00:13:45,439 [winesteam]:wine is not installed
DEBUG    2018-11-25 00:13:45,456 [lutriswindow]:Showing splash screen
DEBUG    2018-11-25 00:13:45,457 [http]:GET https://lutris.net/api/runtime
WARNING  2018-11-25 00:13:46,010 [runtime]:Runtime steam is not available locally
DEBUG    2018-11-25 00:13:46,011 [downloader]:Starting download of:
 https://lutris.nyc3.digitaloceanspaces.com/runtime/steam.tar.bz2
DEBUG    2018-11-25 00:13:46,012 [runtime]:Runtime winetricks is already up to date (locally updated on Cts 24 Kas 2018 21:13:07 GMT, remote created on Paz 28 Eki 2018 08:59:17 )
WARNING  2018-11-25 00:13:46,013 [runtime]:Runtime lib64 is not available locally
DEBUG    2018-11-25 00:13:46,014 [downloader]:Starting download of:
 https://lutris.nyc3.digitaloceanspaces.com/runtime/lib64.tar.bz2
DEBUG    2018-11-25 00:13:46,016 [http]:GET https://lutris.nyc3.digitaloceanspaces.com/runtime/steam.tar.bz2
WARNING  2018-11-25 00:13:46,020 [runtime]:Runtime lib32 is not available locally
DEBUG    2018-11-25 00:13:46,020 [downloader]:Starting download of:
 https://lutris.nyc3.digitaloceanspaces.com/runtime/lib32.tar.bz2
DEBUG    2018-11-25 00:13:46,029 [http]:GET https://lutris.nyc3.digitaloceanspaces.com/runtime/lib64.tar.bz2
DEBUG    2018-11-25 00:13:46,032 [runtime]:Runtime p7zip is already up to date (locally updated on Cts 24 Kas 2018 21:13:06 GMT, remote created on Sal 25 Eki 2016 02:34:44 )
DEBUG    2018-11-25 00:13:46,034 [http]:GET https://lutris.nyc3.digitaloceanspaces.com/runtime/lib32.tar.bz2
DEBUG    2018-11-25 00:13:46,045 [api]:Fetching game library
DEBUG    2018-11-25 00:13:46,183 [lutriswindow]:Showing splash screen
INFO     2018-11-25 00:13:46,183 [lutriswindow]:Setting up view for first run
WARNING  2018-11-25 00:13:50,898 [winesteam]:wine is not installed
WARNING  2018-11-25 00:13:50,906 [winesteam]:wine is not installed
DEBUG    2018-11-25 00:14:00,446 [http]:GET https://lutris.net/api/runners/wine
INFO     2018-11-25 00:14:34,326 [application]:Shutting down Lutris
DEBUG    2018-11-25 00:14:34,329 [downloader]:Download of https://lutris.nyc3.digitaloceanspaces.com/runtime/steam.tar.bz2 cancelled
DEBUG    2018-11-25 00:14:34,331 [downloader]:Download of https://lutris.nyc3.digitaloceanspaces.com/runtime/lib64.tar.bz2 cancelled
DEBUG    2018-11-25 00:14:34,332 [downloader]:Download of https://lutris.nyc3.digitaloceanspaces.com/runtime/lib32.tar.bz2 cancelled
INFO     2018-11-25 00:14:34,347 [application]:Shutting down Lutris`

So it is somewhat ssl related.

**Comment by ironrock361** [comment]
+1 Turkish citizen here. ISP is Turk Telekom.

In Ubuntu 18.10 there is no problem but in Ubuntu 18.04 and Elementary OS 5.0 (which is based on Ubuntu 18.04) I can reproduce.

I see same IP (104.27.187.245) when I ping to lutris.net.

**Comment by Leopard1907** [comment]
https://lists.ubuntu.com/archives/ubuntu-devel/2018-December/040567.html

That should solve the problem on 18.04 base

**Comment by oktay454** [comment]
This is a problem with the desktop environment.
env LC_ALL = C lutris
When running with this command, the problem leaves.

**Comment by Leopard1907** [comment]
So for people who are experiencing this:

For Ubuntu 18.04 base ( Linux Mint 19 etc) 

`sudo add-apt-repository ppa:mgrocock/openssl`

For Ubuntu 16.04 base ( Mint 18 )

`sudo add-apt-repository ppa:carsten-uppenbrink-net/postfix`

These PPA's are containing libssl 1.1.1 and it fixes the issue.

**Comment by oktay454** [comment]
> So for people who are experiencing this:
> 
> For Ubuntu 18.04 base ( Linux Mint 19 etc)
> 
> `sudo add-apt-repository ppa:mgrocock/openssl`
> 
> For Ubuntu 16.04 base ( Mint 18 )
> 
> `sudo add-apt-repository ppa:carsten-uppenbrink-net/postfix`
> 
> These PPA's are containing libssl 1.1.1 and it fixes the issue.

**Turkish**
Pardus kullanıyorum. Pardus ise Debian 9 tabanına sahip.
Pardus'ta sorunu bu şekilde çözdük. Ama uçbirimden sadece lutris komutunu verdiğimizde açılmıyor. Benzeri bir sorun Steam'de de yaşanıyor. Sistem dili ile uyuşmadığı için yukarıda verdiğim komut ile sistem ayarını görmezden geliyor.

**English**
I using Pardus 17. Pardus is based on Debian 9
Pardus solved the problem in this way. But it doesn't open from the terminal only when we give the command of lutris. A similar problem is taking place on Steam. Because it does not match the system language, it ignores the system setting with the command I gave above.

**Note: Translated by Google Translate.**

**Comment by Leopard1907** [comment]
Turkish :

Aslında Steam'i o şekilde başlatmaya artık gerek yok. Beta kanala geçmeyi deneyin isterseniz.

https://forum.linuxmint.net.tr/index.php?topic=9280.0

Konuda soruna dair Github linki yer almakta. Uzun zaman önce rapor etmiştim.

**Comment by strycore** [comment]
I've documented the problem here: https://lutris.net/faq#ssl-issue

@Leopard1907 let me know if there is anything else I can put in the FAQ to help with this isue.

**Comment by kelebek333** [comment]
Hi @strycore ,

Could You update FAQ page for ssl fix of Ubuntu 16.04. Current PPA repo of Ubuntu 16.04.x base is the following.

`sudo add-apt-repository ppa:carsten-uppenbrink-net/openssl`

**Comment by TMiguelT** [comment]
I'm also getting this error.

> your linux distribution
```
$ lsb_release --description
Description:	Ubuntu 18.04.2 LTS
$ uname -r -s -o -i -m
Linux 4.15.0-46-generic x86_64 x86_64 GNU/Linux
```
> the version of libssl installed on your system
```
apt list --installed | grep openssl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

openssl/bionic,now 1.1.1-1ubuntu2.1~ppa1bionic1 amd64 [installed]
```

> your geographical location (country or region is enough)

Australia

> the ip address you get when pinging lutris.net

```
dig lutris.net

; <<>> DiG 9.11.3-1ubuntu1.5-Ubuntu <<>> lutris.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57609
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
; COOKIE: 2d3da12fdf30fa74 (echoed)
;; QUESTION SECTION:
;lutris.net.			IN	A

;; ANSWER SECTION:
lutris.net.		294	IN	A	104.27.186.245
lutris.net.		294	IN	A	104.27.187.245

;; Query time: 0 msec
;; SERVER: 172.16.100.33#53(172.16.100.33)
;; WHEN: Thu Mar 28 11:54:08 AEDT 2019
;; MSG SIZE  rcvd: 83
```

**Comment by kelebek333** [comment]
@TMiguelT , can you share the output of the following command?

`openssl version -a`

Is the issue solving by running with the following command?

`env LC_ALL=C lutris`

**Comment by TMiguelT** [comment]
```
$ openssl version -a


OpenSSL 1.1.1  11 Sep 2018
built on: Wed Jan  9 18:35:33 2019 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-WVSN75/openssl-1.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific
```

And yes, setting that variable seems to have fixed the problem:

```
$ env LC_ALL=C lutris --install mtga.json

2019-03-29 17:03:42,708: Running Lutris 0.5.1.3
2019-03-29 17:03:42,709: Using Intel Open Source Technology Center
2019-03-29 17:03:42,709: Running Mesa driver 18.2.2 on Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)  (0x5916)
2019-03-29 17:03:42,709: GPU: 8086:5916 1028:07A0 using i915 drivers
2019-03-29 17:03:42,710: Vulkan is not available or your system isn't Vulkan capable
2019-03-29 17:03:42,711: Updating DXVK versions
2019-03-29 17:03:47,434: Getting runner information for wine(version: tkg-unity-4.1-x86_64)
2019-03-29 17:04:02,208: Downloading file 1 of 1
2019-03-29 17:04:02,211: Creating a win32 prefix in /home/michael/Games/magic-the-gathering-arena
2019-03-29 17:04:13,864: win32 Prefix created in /home/michael/Games/magic-the-gathering-arena
Running /home/michael/.local/share/lutris/runtime/winetricks/winetricks --unattended dotnet471
Using winetricks 20190310-next - sha256sum: ba32734c7e69ae53929d92184fadcea66836cd5c9ba43694e153b53522d74669 with wine-4.1 ( Staging Esync ) and WINEARCH=win32
Executing w_do_call dotnet471
Executing load_dotnet471 
Executing mkdir -p /home/michael/.cache/winetricks/dotnet471
Executing cd /home/michael/.cache/winetricks/dotnet471
Downloading http://download.microsoft.com/download/9/E/6/9E63300C-0941-4B45-A0EC-0008F96DD480/NDP471-KB4033342-x86-x64-AllOS-ENU.exe to /home/michael/.cache/winetricks/dotnet471

...
```

(the download seems to work)

**Comment by kelebek333** [comment]
@TMiguelT , did you install openssl by compiling from source file, before installing from the PPA repository.

**Comment by TMiguelT** [comment]
No, I'm pretty sure I had the default Ubuntu version (from 18.04), and then I added the PPA. But I had the same error in both cases

**Comment by TMiguelT** [comment]
Is there some way to make sure?

**Comment by kelebek333** [comment]
This issue in my system is solved by updating the openssl version. I am using Linux Mint 19.1 (lutris 0.5.1.3) with Turkish locale. Your system may be regressing for a different reason.

If you want, you can make the LC_ALL=C variable permanent in the following way.

Open lutris desktop file with following command.

`sudo nano /usr/share/applications/net.lutris.Lutris.desktop`

After, find below line,

`Exec=lutris %U`

and can change it as following.

`Exec=env LC=ALL=C lutris %U`

Finally save the file.

**Comment by strycore** [comment]
I recommend updating to a Ubuntu 19.04 based distro when it is released later this month. This distribution won't have any of those issues and provides a very solid stack out of the box (Linux 5.0, Mesa 19.0 and Wine 4.0)

**Comment by moar55** [comment]
Hello, I just wanted to say that runnign the following commands fixed my issue:
```
sudo update-ca-certificates --fresh
export SSL_CERT_DIR=/etc/ssl/certs
```

**Comment by moar55** [comment]
Maybe add it to the #faq? 
Obviously, one need to have ca-certificates first to begin with
`sudo apt install ca-certificates`
