### ISSUE TITLE
Cannot log in to Epic Games Store

### ISSUE THREAD

**Issue by PatientAllison** [lutris/lutris#4869]
### Bug description

Two possible workflows:

Attempt to log in directly via Epic Window
Attempt to log in with an external service such as google (all of them give the same result)

Neither work

### How to Reproduce

Direct via Epic:

1. Launch lutris with `lutris -d`
2. Click on picture of a person next to Epic Games Store
3. Click "Sign in with Epic Games"
4. Enter username and password
5. Epic window freezes without logging in
6. Lutris itself does not crash

Via external service:
1. Launch lutris with `lutris -d`
2. Click on picture of a person next to Epic Games Store
3. Click "Sign in with Google"
4. A blank gray window will open and nothing will ever load
5. Closing this window crashes Lutris

### Expected behavior

Direct via Epic:
Sign into Epic

Via external service:
External service window should load

### Log output

```shell
Direct via Epic:

INFO     2023-05-23 02:25:39,593 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-05-23 02:25:39,623 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-05-23 02:25:39,661 [startup.check_driver:57]:Using NVIDIA drivers 530.41.03 for x86_64
INFO     2023-05-23 02:25:39,661 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 4090
INFO     2023-05-23 02:25:39,661 [startup.check_driver:77]:GPU: 10DE:2684 1462:5104 (nvidia drivers)
DEBUG    2023-05-23 02:25:39,869 [lutriswindow.update_store:448]:Showing 0 games
INFO     2023-05-23 02:25:39,874 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-05-23 02:25:42,439 [base.login:332]:Connecting to Epic Games Store
ERROR    2023-05-23 02:26:05,112 [style_manager._new_for_bus_cb:79]:Unable to start Settings portal: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.portal.Desktop: Timeout was reached (24)

Via external service:

INFO     2023-05-23 02:29:39,940 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-05-23 02:29:39,969 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-05-23 02:29:40,007 [startup.check_driver:57]:Using NVIDIA drivers 530.41.03 for x86_64
INFO     2023-05-23 02:29:40,007 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 4090
INFO     2023-05-23 02:29:40,007 [startup.check_driver:77]:GPU: 10DE:2684 1462:5104 (nvidia drivers)
DEBUG    2023-05-23 02:29:40,207 [lutriswindow.update_store:448]:Showing 0 games
INFO     2023-05-23 02:29:40,212 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-05-23 02:29:42,143 [base.login:332]:Connecting to Epic Games Store
[1]    17184 segmentation fault (core dumped)  lutris -d
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.3.3-arch1-1
Desktop:         XFCE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 530.41.03
OpenGL Core:     4.6.0 NVIDIA 530.41.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 530.41.03
Vulkan:          Supported
```

### Media (optional)

Frozen epic window (note that I have redacted my email and password)

![epicfrozen](https://github.com/lutris/lutris/assets/81192901/3205d05c-00cc-43a9-85f7-e0ea807f24b0)

Grey window when trying to open external service (closing the "Loading..." window crashes lutris with a segfault)
![greyepic](https://github.com/lutris/lutris/assets/81192901/27c15e01-8e86-44b3-871f-2c19933736fe)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by PatientAllison** [comment]
The google window now pops up, but I can't get very far into it. First of all, when opening it, the window appears gray at first, and only renders properly after resizing it slightly.

Before resize:
![signingoogle](https://github.com/lutris/lutris/assets/81192901/60bafb52-68fa-49bd-ab0f-1fdeaa922176)

After Resize:
![afterresize](https://github.com/lutris/lutris/assets/81192901/68db5460-770c-416e-80ff-0590c7530498)

Then, after entering email, clicking the next causes the screen to freeze, similar to signing into Epic directly.
![hitnext](https://github.com/lutris/lutris/assets/81192901/e4977e50-d71f-49f4-a5fd-9bfbd397c0ac)

Log of above (note the webkit error that appears after lutris is already closed):

```
patientallison@arch ~ % lutris -d
INFO     2023-05-24 22:09:46,019 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-05-24 22:09:46,021 [startup.check_driver:65]:Using NVIDIA drivers 530.41.03 for x86_64
INFO     2023-05-24 22:09:46,021 [startup.check_driver:69]:GPU: NVIDIA GeForce RTX 4090
INFO     2023-05-24 22:09:46,021 [startup.check_driver:85]:GPU: 10DE:2684 1462:5104 (nvidia drivers)
WARNING  2023-05-24 22:09:46,054 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
WARNING  2023-05-24 22:09:46,055 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
DEBUG    2023-05-24 22:09:46,213 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-24 22:09:46,271 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-05-24 22:09:48,186 [base.login:358]:Connecting to Epic Games Store
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/style_manager.py", line 68, in _new_for_bus_cb
    proxy = obj.new_for_bus_finish(result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.portal.Desktop: Timeout was reached (24)
INFO     2023-05-24 22:15:01,568 [application.do_shutdown:960]:Shutting down Lutris
patientallison@arch ~ % 
** (WebKitWebProcess:14278): ERROR **: 22:15:08.843: WebProcess didn't exit as expected after the UI process connection was closed
```

**Comment by PatientAllison** [comment]
If you hit enter while still in the text box, however, you can get to the next screen. However, it won't let you type the password or respond at all.

![canttype](https://github.com/lutris/lutris/assets/81192901/b2f043f5-fd37-4c65-a4b9-53c20548c537)

On precisely one occasion, it actually did let me type my password! However, on hitting enter, it still froze.
![gottopassword](https://github.com/lutris/lutris/assets/81192901/35f7cbe6-0704-492a-b1d2-99d543259cc2)


Log of these runs (I tried a few times to replicate being able to type, to no avail, which is why it's quite a bit longer. I'm not sure which one was the one where it actually let me type.):
```
INFO     2023-05-24 22:19:59,543 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-05-24 22:19:59,545 [startup.check_driver:65]:Using NVIDIA drivers 530.41.03 for x86_64
INFO     2023-05-24 22:19:59,545 [startup.check_driver:69]:GPU: NVIDIA GeForce RTX 4090
INFO     2023-05-24 22:19:59,545 [startup.check_driver:85]:GPU: 10DE:2684 1462:5104 (nvidia drivers)
WARNING  2023-05-24 22:19:59,578 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
WARNING  2023-05-24 22:19:59,579 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
DEBUG    2023-05-24 22:19:59,796 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-24 22:19:59,855 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-05-24 22:20:02,004 [base.wipe_game_cache:369]:Deleting egs cache /home/patientallison/.cache/lutris/egs-library.json
DEBUG    2023-05-24 22:20:02,004 [base.wipe_game_cache:174]:Deleting games from service-games for egs
DEBUG    2023-05-24 22:20:02,005 [base.logout:384]:logged out from egs
DEBUG    2023-05-24 22:20:02,583 [base.login:358]:Connecting to Epic Games Store
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/style_manager.py", line 68, in _new_for_bus_cb
    proxy = obj.new_for_bus_finish(result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.portal.Desktop: Timeout was reached (24)
DEBUG    2023-05-24 22:20:27,111 [base.wipe_game_cache:369]:Deleting egs cache /home/patientallison/.cache/lutris/egs-library.json
DEBUG    2023-05-24 22:20:27,111 [base.wipe_game_cache:174]:Deleting games from service-games for egs
DEBUG    2023-05-24 22:20:27,113 [base.logout:384]:logged out from egs
DEBUG    2023-05-24 22:20:27,557 [base.login:358]:Connecting to Epic Games Store
DEBUG    2023-05-24 22:20:58,067 [base.wipe_game_cache:369]:Deleting egs cache /home/patientallison/.cache/lutris/egs-library.json
DEBUG    2023-05-24 22:20:58,068 [base.wipe_game_cache:174]:Deleting games from service-games for egs
DEBUG    2023-05-24 22:20:58,069 [base.logout:384]:logged out from egs
DEBUG    2023-05-24 22:20:58,416 [base.login:358]:Connecting to Epic Games Store
DEBUG    2023-05-24 22:21:34,944 [base.wipe_game_cache:369]:Deleting egs cache /home/patientallison/.cache/lutris/egs-library.json
DEBUG    2023-05-24 22:21:34,944 [base.wipe_game_cache:174]:Deleting games from service-games for egs
DEBUG    2023-05-24 22:21:34,946 [base.logout:384]:logged out from egs
DEBUG    2023-05-24 22:21:35,285 [base.login:358]:Connecting to Epic Games Store
DEBUG    2023-05-24 22:21:54,275 [base.wipe_game_cache:369]:Deleting egs cache /home/patientallison/.cache/lutris/egs-library.json
DEBUG    2023-05-24 22:21:54,275 [base.wipe_game_cache:174]:Deleting games from service-games for egs
DEBUG    2023-05-24 22:21:54,275 [base.logout:384]:logged out from egs
DEBUG    2023-05-24 22:21:54,583 [base.login:358]:Connecting to Epic Games Store

** (WebKitWebProcess:16264): ERROR **: 22:22:02.984: WebProcess didn't exit as expected after the UI process connection was closed
DEBUG    2023-05-24 22:23:36,422 [base.wipe_game_cache:369]:Deleting egs cache /home/patientallison/.cache/lutris/egs-library.json
DEBUG    2023-05-24 22:23:36,422 [base.wipe_game_cache:174]:Deleting games from service-games for egs
DEBUG    2023-05-24 22:23:36,423 [base.logout:384]:logged out from egs
DEBUG    2023-05-24 22:23:36,834 [base.login:358]:Connecting to Epic Games Store

** (WebKitWebProcess:16386): ERROR **: 22:23:45.090: WebProcess didn't exit as expected after the UI process connection was closed
DEBUG    2023-05-24 22:24:03,261 [base.wipe_game_cache:369]:Deleting egs cache /home/patientallison/.cache/lutris/egs-library.json
DEBUG    2023-05-24 22:24:03,262 [base.wipe_game_cache:174]:Deleting games from service-games for egs
DEBUG    2023-05-24 22:24:03,263 [base.logout:384]:logged out from egs
DEBUG    2023-05-24 22:24:03,587 [base.login:358]:Connecting to Epic Games Store
INFO     2023-05-24 22:25:15,951 [application.do_shutdown:960]:Shutting down Lutris
```

**Comment by PatientAllison** [comment]
As for issue #4853, I looked at the conversation and am having some trouble parsing it. I see some stuff about dark mode? I'm not actually using lutris's dark mode, I'm using the `arc-dark` gtk theme and don't have a light variant installed, so the dark mode toggle in lutris's settings does nothing and I don't have it checked, and I'm not sure what it has to do with Epic login other than a similar error message.

**Comment by strycore** [comment]
Ok, it now seems that both methods of authentication are running into the same problem.
Note that on my setup, I'm able to log in using both methods. 

The similarity with #4853 is related to the Portal service

```Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/style_manager.py", line 68, in _new_for_bus_cb
    proxy = obj.new_for_bus_finish(result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.portal.Desktop: Timeout was reached (24)
```

Although, they are slightly different. One is timing out while the other can't find the service at all.

I'm not able to reproduce either bug on fresh VMs of Arch and Kubuntu 20.04

**Comment by strycore** [comment]
There's also this error:

`** (WebKitWebProcess:16386): ERROR **: 22:23:45.090: WebProcess didn't exit as expected after the UI process connection was closed`

Not sure what to make of that, I suspect it's a side effect of the bug you are seeing, not the cause.

**Comment by gardotd426** [comment]
I am also seeing this bug. I could previously log in, until recently. I have the exact same behavior as @PatientAllison. When I try to log in, the spinny wheel just spins forever. 

I can log in to all other services.

**Comment by gardotd426** [comment]
Actually no, @PatienAllison is right, the wheel doesn't just spin, it starts to spin and the window freezes. 

`lutris -d` output while trying to log in:

```
DEBUG    2023-05-26 05:55:56,385 [base.wipe_game_cache:174]:Deleting games from service-games for egs
WARNING  2023-05-26 05:55:56,392 [egs.load:309]:EGS Token expired
ERROR    2023-05-26 05:55:56,392 [jobs.target:36]:Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7ff2bac43740>: <class 'lutris.services.base.AuthTokenExpired'>
  File "/usr/lib/python3.11/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/services/base.py", line 141, in do_reload
    self.load()
  File "/usr/lib/python3.11/site-packages/lutris/services/egs.py", line 310, in load
    raise AuthTokenExpired from ex
DEBUG    2023-05-26 05:55:56,393 [base.wipe_game_cache:369]:Deleting egs cache /home/matt/.cache/lutris/egs-library.json
DEBUG    2023-05-26 05:55:56,393 [base.wipe_game_cache:174]:Deleting games from service-games for egs
DEBUG    2023-05-26 05:55:56,393 [base.logout:384]:logged out from egs
DEBUG    2023-05-26 05:55:56,394 [base.login:358]:Connecting to Epic Games Store
```

**Comment by strycore** [comment]
Since we're allowing 2 version of WebKit2 (4.0 and 4.1) could it be that the older version no longer works?

**Comment by gardotd426** [comment]
I force-uninstalled each of them (both of them are dependencies for several packages I have installed) one at a time and tried logging in, same behavior with each one. I also have webkit2gtk-5.0 installed as well, could that be messing with anything?

Right now `lutris -d &` in the terminal doesn't even give me any errors when the EGS window freezes.

**Comment by gardotd426** [comment]
Welp, just uninstalled 5.0 and just left 4.1 and 4.0, still same behavior.

**Comment by strycore** [comment]
Since it's just the freeze now, I'll close this as duplicate of #4783

**Comment by gardotd426** [comment]
I'm confused. Trying to log in via google still crashes Lutris.

**Comment by strycore** [comment]
yes, you're now running into the same crash when using both email or google to log in.

before that, Google auth used to crash in a different way,
Now, I'm able to log in using both methods and trying to figure out what causes webkit to crash on some setups.
(Currently suspecting the Nvidia driver)

**Comment by PatientAllison** [comment]
I'm curious, why would what graphics driver you're using affect logging in? It would make sense if it was causing issues with the games themselves, but just a login?

**Comment by gardotd426** [comment]
I've been able to log in on this exact graphics driver before. It was a Lutris update that broke things. 

I guess I can try to bisect the problem and see if I can find a bad commit/set of commits.

**Comment by gardotd426** [comment]
So, I've found the bad package and the first bad *package* version, now I need to manually bisect it. 

It's `webkit2gtk-4.1`. I downgraded every webkit package and then upgraded one at a time til I found the culprit. 2.38.5 is the last good version of `webkit2gtk-4.1`, it allows you to log in to EGS. Other webkit2gtk versions don't have any affect.

**Comment by gardotd426** [comment]
Well, I can't bisect anything, because all the good versions fail to
compile, there's a patch in the current upstream Arch PKGBUILD to fix
compilation errors, but that patch doesn't work on the older versions, and
I tried with gcc12, but no dice. So I'm kind of stuck at an impasse here,
unless there's any suggestions.

**Comment by strycore** [comment]
I posted a script here https://github.com/lutris/lutris/issues/4783#issuecomment-1566588739 to demonstrate the issue. When using newer versions of Webkit2gtk, the issue is fixed.

**Comment by strycore** [comment]
disabling WebGL fixes the issue!
