### ISSUE TITLE
Lutris crashes after update to 0.5.0 (playtime)

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1698]
From a user on discord:
```
INFO     2019-02-02 10:25:28,606 [application.do_command_line:222]:Running Lutris 0.5.0
INFO     2019-02-02 10:25:28,607 [startup.check_driver:43]:Using NVIDIA drivers 396.54 for x86_64
INFO     2019-02-02 10:25:28,607 [startup.check_driver:47]:GPU: GeForce GTX 1070 Ti
INFO     2019-02-02 10:25:28,607 [startup.check_driver:63]:GPU: 10DE:1B82 1043:861E using nvidia drivers
INFO     2019-02-02 10:25:28,653 [startup.check_vulkan:84]:Vulkan is supported
ERROR    2019-02-02 10:25:28,654 [game.__init__:69]:Invalid playtime value 0.0 hrs
ERROR    2019-02-02 10:25:28,656 [startup.fill_missing_platforms:98]:Providing missing platorm for game super-smash-bros-melee
WARNING  2019-02-02 10:25:28,656 [game.set_platform_from_runner:193]:Can't get platform for runner Dolphin
DEBUG    2019-02-02 10:25:28,656 [game.save:201]:Saving Super Smash Bros. Melee (dolphin)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 223, in do_command_line
    run_all_checks()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 109, in run_all_checks
    fill_missing_platforms()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 100, in fill_missing_platforms
    game.save(metadata_only=True)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 216, in save
    playtime=self.playtime,
AttributeError: 'Game' object has no attribute 'playtime'
INFO     2019-02-02 10:25:28,688 [application.do_shutdown:439]:Shutting down Lutris
```
I looked into their `pga.db` and the playtime value for that game is `0.0 hrs`.

**Comment by tannisroot** [comment]
I fixed it by changing their pga.db and deleting the value for playtime.

**Comment by MGThePro** [comment]
I'm having the same problem. Can you explain how and what you changed in your pga.db?

**Comment by tannisroot** [comment]
I used an app to edit the database and removed the value for playtime.

**Comment by nemesus** [comment]
```
+      self.playtime = 0.0
        try:
            self.playtime = float(game_data.get("playtime") or 0.0)
        except ValueError:
            logger.error("Invalid playtime value %s", game_data.get("playtime"))
```

Fixed with the above modification, allowing playtime to be set to 0.0 as intended even if there is an issue with the stored playtime value.
