### PR TITLE
Fix AtributeError when installing wine games (fixes #1274)

### LINKED ISSUE #1274: AttributeError("module 'lutris.runners.wine' has no attribute 'get_wine_version_exe'")
Happens when installing anything with the Wine runner. [Happens on latest commit as of writing.](https://github.com/lutris/lutris/commit/ca9b4d5d3e7e130c000bec6474704a373e352e9c)

### PR DESCRIPTION
**Pull request by manuelVo**
This fixes a regression introduced by a77ce818 (`get_wine_version_exe` moved to `lutris.util.wine`)

### CODE REVIEW

**Comment by sigmaSd** [comment]
this [https://github.com/lutris/lutris/blob/master/lutris/installer/commands.py#L380](https://github.com/lutris/lutris/blob/master/lutris/installer/commands.py#L380) needs to be modified too

**Comment by sigmaSd** [comment]
this [https://github.com/lutris/lutris/blob/master/lutris/installer/interpreter.py#L832](https://github.com/lutris/lutris/blob/master/lutris/installer/interpreter.py#L832) too needs modfication

**Comment by manuelVo** [comment]
Right. I modified that as well.
